# Generated by Django 3.2.7 on 2021-09-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listentry',
            old_name='list_id',
            new_name='list_obj',
        ),
    ]
